# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

# luks root partition_____________________________________________________________________________________

  boot.initrd.luks.devices."nixos".device = "/dev/disk/by-uuid/676b9347-92b0-49db-af45-3cae0c572fc1";

#luks home partition________________________________________________________________________________________

  boot.initrd.luks.devices."home".device = "/dev/disk/by-uuid/bf684032-3e2a-4f31-aeb8-c608c38348bd";

# boot partition_____________________________________________________________________________________________

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/05A2-1D59";
      fsType = "vfat";
    };

# root partition_____________________________________________________________________________________________

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6459b2bd-63b0-43a7-b9b2-dfca2502ec7d";
      fsType = "ext4";
    };

# home partition______________________________________________________________________________________________

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/2b48f801-f43a-4f69-927b-35ec2552d80f";
      fsType = "ext4";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

#NAME                                          FSTYPE      FSVER LABEL          UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
#sda                                                                                                                                
#├─sda1                                        crypto_LUKS 1                    bf684032-3e2a-4f31-aeb8-c608c38348bd                
#│ └─luks-bf684032-3e2a-4f31-aeb8-c608c38348bd ext4        1.0   home_partition 2b48f801-f43a-4f69-927b-35ec2552d80f  363,9G     0% /home
#├─sda2                                        crypto_LUKS 1                    676b9347-92b0-49db-af45-3cae0c572fc1                
#│ └─luks-676b9347-92b0-49db-af45-3cae0c572fc1 ext4        1.0   root_partition 6459b2bd-63b0-43a7-b9b2-dfca2502ec7d   32,8G    50% /nix/store
#│                                                                                                                                  /
#└─sda3                                        vfat        FAT32                05A2-1D59                               484M    12% /boot
